version: '3'
services:
  # db:
  #   image: mysql:8
  #   container_name: avocado_db
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   env_file: ./backend/docker-backend.env
  #   volumes:
  #     - mysql_data:/var/lib/mysqla

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend:/app

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "8379:6379"
        

         # nginx:
         #   image: nginx:latest
         #   ports:
         #     - "443:443"
         #     - "80:80"
         #   volumes:
         #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
         #         - ./nginx.conf:/etc/nginx/nginx.conf
         #         - ./certs:/etc/letsencrypt

# 로컬 테스트 때 주석 해제
  # openvidu:
  #   image: openvidu/openvidu-dev:2.28.0
  #   container_name: avocado_openvidu
  #   ports:
  #     - "4443:4443"
  #   environment:
  #     - OPENVIDU_SECRET=ssafy

# volumes:
#   mysql_data:
